### ISSUE TITLE
spark-worker-1     | /usr/bin/env: ‘bash\r’: No such file or directory

### ISSUE THREAD

**Issue by RamesChan** [athanan/spark-local-dev#3]
I have a problem after clone and follow your Readme 
![image](https://github.com/user-attachments/assets/674f401b-9419-45fa-9239-34aa764d8c4a)

when I "docker compose up"
![image](https://github.com/user-attachments/assets/97082953-7721-4c15-a182-2a2ab2ba8bfd)

I check in docker desktop and saw many container Exited. Please Help me.
![image](https://github.com/user-attachments/assets/54babf26-ac77-4f8c-8f69-b8a43d39048b)

**Comment by athanan** [comment]
@RamesChan I've cleaned my docker image, and rebuild everything from zero. It works fine. Can I see stdout of each failed container?

**Comment by RamesChan** [comment]
here.
![image](https://github.com/user-attachments/assets/b973860c-c7be-4d36-9cad-237a35353ea6)

all spark are the same.
![image](https://github.com/user-attachments/assets/6c500421-78c9-431b-8d19-a88f735073b0)

![image](https://github.com/user-attachments/assets/8998161d-6219-4250-9b4a-5800b70f1497)

![image](https://github.com/user-attachments/assets/7008396b-eeda-4a50-9422-5cf4fe1c00ea)

I'm not change anything.
![image](https://github.com/user-attachments/assets/ef608cd8-273f-41fc-a5b2-c1b829eb6efc)

**Comment by athanan** [comment]
@RamesChan can you rebuild the image? And re-compose? If it does not work. You might need to debug what’s inside your built image (shell into the container).

**Comment by RamesChan** [comment]
@athanan I already fix this issue. the root cause is about types of **line-ending characters**. when I open .sh file type is **CRLF** (image below)

![image](https://github.com/user-attachments/assets/001afae5-1d16-4592-b24d-6f5068f14d8d)

![image](https://github.com/user-attachments/assets/3c6512b2-27e0-443b-af95-1c34ffba1602)

Maybe **CRLF** is the type for window that why it's have a problem when copy and run it in **Linux or Unix-based systems** (I'm not sure sorry).

I solved this problem by simply changing the file type.

Thank you so much for your support and sharing with us.

**Comment by athanan** [comment]
@RamesChan thanks for sharing tour findings and good to hear that the problem was solved~
